using System;
using System.Collections.Generic;
using System.IO;

namespace SroMapToNavmeshData
{
	// Token: 0x02000002 RID: 2
	internal static class GlobalData
	{
		// Token: 0x06000001 RID: 1 RVA: 0x00002050 File Offset: 0x00000250
		public static void LoadObjectIfo()
		{
			int num = 0;
			string text = string.Format("{0}\\Map\\object.ifo", Directory.GetCurrentDirectory());
			StreamReader streamReader = new StreamReader(text);
			bool flag = !File.Exists(text);
			if (flag)
			{
				throw new InvalidOperationException(string.Format("File {0} not found.", text));
			}
			string text2;
			while ((text2 = streamReader.ReadLine()) != null)
			{
				string[] array = text2.Split(new char[]
				{
					' '
				});
				bool flag2 = num > 1;
				if (flag2)
				{
					string[] array2 = text2.Split(new char[]
					{
						'"'
					});
					GlobalData.objectIfo[int.Parse(array[0])] = array2[1];
				}
				num++;
			}
			streamReader.Close();
		}

		// Token: 0x04000001 RID: 1
		public static Dictionary<int, string> objectIfo = new Dictionary<int, string>();

		// Token: 0x04000002 RID: 2
		public static string[] EventZoneFlagObjects = new string[]
		{
			"headquarters_00.bsr",
			"big_defensive_position_00.bsr",
			"fort_stone_ct.bsr",
			"barricade_04.bsr",
			"barricade_03.bsr",
			"fort_stone_ja.bsr",
			"desert_start01.bsr",
			"palace_start01.bsr",
			"palace_start02.bsr",
			"desert_start02.bsr",
			"togui_door02.bsr",
			"togui_door01.bsr",
			"piety_e12_door.bsr",
			"piety_golddoor.bsr"
		};

		// Token: 0x04000003 RID: 3
		public static string[] NoCollisionFlagObjects = new string[]
		{
			"rock_m_tree04_01.bsr",
			"rock_m_smalltree05_b_01.bsr",
			"rock_mt_stone08_02.bsr",
			"rock_mt_stone06_01.bsr",
			"rock_mt_stone_s02_01.bsr",
			"oas_kk_snow_pine03_01.bsr",
			"rock_m_smalltree05_m_01.bsr",
			"rock_mt_stone01_01.bsr",
			"rock_mt_stone03_06.bsr",
			"rock_m_tree022_01.bsr",
			"rock_m_tree033_01.bsr",
			"rock_mt_stone04_07.bsr",
			"rock_mt_stone04_06.bsr",
			"oas_kk_snow_pine05_01.bsr",
			"oas_kk_small_tree03_01.bsr",
			"oas_kk_fld_sanga07.bsr",
			"oas_kk_fld_stone02.bsr",
			"rock_m_branch07_01.bsr",
			"rock_mt_stone04_05.bsr",
			"rock_mt_stone04_01.bsr",
			"oas_kk_snow_pine04_01.bsr",
			"oas_kk_fld_sanga06.bsr",
			"oas_kk_smalltree04_01.bsr",
			"oas_kk_fld_stone04.bsr",
			"rock_mt_stone01_03.bsr",
			"rock_mt_stone_m01_01.bsr",
			"rock_mt_stoneb02_01.bsr",
			"rock_mt_stone07_01.bsr",
			"rock_mt_stone07_04.bsr",
			"rock_mt_stone08_01.bsr",
			"rock_mt_stone08_04.bsr",
			"rock_mt_stone08_03.bsr",
			"rock_mt_stone03_03.bsr",
			"rock_mt_stone03_07.bsr",
			"rock_m_branch08_01.bsr",
			"oas_kara_ruins_brick.bsr",
			"rock_mt_stone02_01.bsr",
			"rock_mt_stone02_04.bsr",
			"rock_mt_stone01_02.bsr",
			"oas_kara_tree03.bsr",
			"oas_kara_tree04.bsr",
			"oas_kara_cwall_gidun01.bsr",
			"oas_kara_tree02.bsr",
			"rock_mt_wingtribe_tree02_01.bsr",
			"rock_mt_wingtribe_tree05_01.bsr",
			"rock_mt_wingtribe_tree01.bsr",
			"oas_kara_tree01.bsr",
			"oas_hot_rock_l_01.bsr",
			"oas_tarim_guknest_bone01.bsr",
			"oas_tarim_rock_l_01.bsr",
			"oas_tarim_rock_l_05.bsr",
			"rock_mt_goatobj_05_1.bsr",
			"rock_mt_wingtribe_tree03.bsr",
			"rock_mt_wingtribe_tree04.bsr",
			"rock_mt_stone03_02.bsr",
			"oas_kara_obj04.bsr",
			"oas_kara_obj01.bsr",
			"tre_palm02_02.bsr",
			"tre_palm02_1.bsr",
			"oas_tarim_rob_tower02_01.bsr",
			"oas_tarim_rock_l_04.bsr",
			"oas_tarim_plt_tre_y01_01.bsr",
			"tre_tree03.bsr",
			"tre_tree02.bsr",
			"tre_tree09.bsr",
			"tre_pine09.bsr",
			"rock_mt_goat01_01.bsr",
			"oas_tarim_rob_bigfire01.bsr",
			"tre_tree05.bsr",
			"stone_field03.bsr",
			"stone_field04.bsr",
			"tre_pine05.bsr",
			"tre_bank01_big.bsr",
			"cj_graveyard_stonewall02.bsr",
			"stone_cliff01_03.bsr",
			"rock_mt_goatobj_02_1.bsr",
			"oas_kk_snow_pine02.bsr",
			"oas_kara_obj06.bsr",
			"oas_tarim_rob_smallfire01.bsr",
			"cj_thiefvill_house_03_01.bsr",
			"cj_thiefvill_side_01.bsr",
			"tre_leaf01.bsr",
			"cj_graveyard_fence01.bsr",
			"cj_graveyard_tree02.bsr",
			"cj_grave_big_01.bsr",
			"cj_grave_tombstone05_01.bsr",
			"cj_graveyard_tree01.bsr",
			"cj_grave_tombstone08_01.bsr",
			"rock_mt_wingtribe_b_tree06_01.bsr",
			"rock_mt_stone_s03_01.bsr",
			"oas_tarim_thorng01_01.bsr",
			"oas_tarim_rob_s_side02.bsr",
			"w_cd_stumpp02.bsr",
			"oas_tarim_wagon01.bsr",
			"stone_field01.bsr",
			"tre_tree08.bsr",
			"tre_tree01_big.bsr",
			"tre_maple03_big.bsr",
			"tre_willow02.bsr",
			"tre_pine07_03.bsr",
			"cj_grave_tombstone06_01.bsr",
			"oas_kk_fld_ss3.bsr",
			"oas_tarim_house01.bsr",
			"oas_tarim_well.bsr",
			"oas_tarim_wagone.bsr",
			"oas_tarim_xbone01.bsr",
			"tre_maple03_big01.bsr",
			"tre_tree01.bsr",
			"tre_frie01.bsr",
			"cj_ferry_boat_old.bsr",
			"tre_bank02.bsr",
			"cj_deedy03.bsr",
			"cj_grave_tombstone03_01.bsr",
			"cj_grave_tombstone04_01.bsr",
			"rock_mt_stone03_01.bsr",
			"rock_mt_stone03_05.bsr",
			"rock_m_branch06.bsr",
			"oas_hot_rock_s_02.bsr",
			"w_cd_deadtree_03.bsr",
			"oas_tarim_ani_bone.bsr",
			"oas_tarim_rock_s_03.bsr",
			"c_hhm_tree_01.bsr",
			"tre_maple03.bsr",
			"tre_bank01.bsr",
			"tre_pine07_04.bsr",
			"oas_hot_rock_l_03.bsr",
			"w_cd_brhwood03_01.bsr",
			"w_cd_rock_big_01.bsr",
			"c_swamp_tree04.bsr",
			"c_swamp_tree03.bsr",
			"cj_strawcart.bsr",
			"tre_smalltree01.bsr",
			"stone_field05.bsr",
			"tre_pine07_02.bsr",
			"oas_tree_tropic03.bsr",
			"oas_big_tarim_hive02_01.bsr",
			"oas_big_tarim_hive03_01.bsr",
			"w_cd_deadtree_02.bsr",
			"w_cd_rock_s_01.bsr",
			"w_cd_ravi_gorge01_01.bsr",
			"cj_ferry_02.bsr",
			"tre_pine08.bsr",
			"tre_maple01.bsr",
			"tre_maple02.bsr",
			"ruin_takla_cac_l_01_1.bsr",
			"ruin_takla_cac_m_02_1.bsr",
			"ruin_takla_cac_m_07_1.bsr",
			"ruin_takla_cac_m_04_1.bsr",
			"ruin_takla_cac_l_06_1.bsr",
			"ruin_takla_cac_s_16_1.bsr",
			"ruin_takla_cac_l_02_1.bsr",
			"ruin_takla_cac_l_03_1.bsr",
			"ruin_takla_cac_m_10_1.bsr",
			"ruin_takla_cac_l_04_2.bsr",
			"ruin_takla_cac_l_13_1.bsr",
			"ruin_takla_cac_m_17_1.bsr",
			"ruin_takla_cac_m_06_1.bsr",
			"ruin_takla_cac_m_01_1.bsr",
			"ruin_takla_cac_m_14_1.bsr",
			"ruin_takla_cac_s_03_1.bsr",
			"oas_tree_tropic10.bsr",
			"w_cd_twig02_tree01.bsr",
			"w_cd_brhwood01_01.bsr",
			"w_cd_brhwood02_01.bsr",
			"w_cd_rock_l_03.bsr",
			"w_cd_gra_s01.bsr",
			"cj_pal_dam_right.bsr",
			"ruin_takla_tent04_01.bsr",
			"oas_big_tarim_hive01_01.bsr",
			"oas_tarim_rock_s_02.bsr",
			"w_cd_ravi_gorge02_01.bsr",
			"w_cd_ravi_gorge03_01.bsr",
			"w_cd_gra_02.bsr",
			"w_cd_gra_03.bsr",
			"c_swamp_tree05.bsr",
			"tre_willow03.bsr",
			"c_jin_bb_wall.bsr",
			"c_jin_wall.bsr",
			"ruin_takla_ship_01.bsr",
			"ruin_takla_cac_l_11_1.bsr",
			"w_cd_rock_s_02.bsr",
			"w_cd_ravi_b_gorge01_01.bsr",
			"w_cd_tree03big.bsr",
			"cj_sugi_house_b.bsr",
			"rok_nest03.bsr",
			"ruin_takl_rock_b03.bsr",
			"ruin_takla_cac_m_08_1.bsr",
			"w_cd_rock_s_03.bsr",
			"w_cd_tree03.bsr",
			"w_cd_stone_05.bsr",
			"w_cd_stone_04.bsr",
			"c_jin_statue_map.bsr",
			"c_jin_wall3_orwall2.bsr",
			"ruin_takla_portalstone08_01.bsr",
			"ruin_takla_destroyh10_01.bsr",
			"ruin_takla_cac_m_12_1.bsr",
			"ruin_takla_cac_m_26_1.bsr",
			"w_cd_field_budda01.bsr",
			"w_cd_field_budda02.bsr",
			"w_cd_deadtree_01.bsr",
			"w_cd_brhwood05_01.bsr",
			"w_cd_bigtortoise01.bsr",
			"cj_imp_door01.bsr",
			"rok_nest02_01.bsr",
			"ruin_takla_destroyh04_01.bsr",
			"ruin_takla_destroyh03_01.bsr",
			"ruin_takla_palm01.bsr",
			"ruin_takla_cac_l_12_1.bsr",
			"ruin_takla_cac_l_05_1.bsr",
			"w_cd_shrine.bsr",
			"ruin_takla_nia04_1.bsr",
			"ruin_takl_rock_mid05.bsr",
			"ruin_takl_rock_s02.bsr",
			"ruin_takl_rock_mid04.bsr",
			"ruin_takl_rock_mid01.bsr",
			"ruin_takl_rock_s03.bsr",
			"ruin_takl_rock_s04.bsr",
			"ruin_takl_rock_mid03.bsr",
			"ruin_takl_rock_s01.bsr",
			"w_cd_stone_06.bsr",
			"w_cd_tree02.bsr",
			"w_cd_broken_wagon01_01.bsr",
			"w_cd_broken_weap02.bsr",
			"w_cd_bigtortoise02.bsr",
			"ruin_takla_destroyh09_01.bsr",
			"ruin_takl_rock_mid02.bsr",
			"w_cd_tree05.bsr",
			"w_cd_twig01_tree01.bsr",
			"w_cd_stumpp03.bsr",
			"w_cd_hotree03_1.bsr",
			"w_cd_rock_l_02.bsr",
			"w_cd_hotree02.bsr",
			"w_cd_gra_01.bsr",
			"w_cd_brhwood04_01.bsr",
			"euro_esteuro_godfld_bruin01_01.bsr",
			"euro_esteuro_godfld_bruin02_01.bsr",
			"euro_est euro_stbridge01.bsr",
			"euro_esteuro_bigsadtree02.bsr",
			"euro_esteuro_sadtree02_01.bsr",
			"euro_esteuro_bigsadtree01.bsr",
			"euro_esteuro_sadtree01_01.bsr",
			"euro_esteuro_goldh01.bsr",
			"euro_esteuro_viking21.bsr",
			"euro_esteuro_viking08.bsr",
			"euro_est euro_elevated_waterway01.bsr",
			"euro_est euro_elevated_waterway02.bsr",
			"euro_est euro_elevated_waterway03.bsr",
			"euro_esteuro_dantree_03_01.bsr",
			"euro_esteuro_stone02.bsr",
			"cj_ferry_boat_new.bsr",
			"fortress_hotan_brid00_01.bsr",
			"euro_constan_tree01_01.bsr",
			"big_defensive_position_00.bsr",
			"headquarters_00.bsr",
			"fortress_ct_fort_bridge02_04.bsr",
			"euro_constan_house04_h01.bsr",
			"cj_graveyard_tree04.bsr",
			"tre_maple04_big01_brn.bsr",
			"tre_leaf02.bsr",
			"cj_graveyard_tree05.bsr",
			"fort_gate.bsr",
			"guil_jang_stair01_01.bsr",
			"cj_graveyard_tree03.bsr",
			"pha_tree07.bsr",
			"pha_tree03.bsr",
			"pha_burner.bsr",
			"pha_maze1.bsr",
			"pha_tree01.bsr",
			"pha_tree02.bsr",
			"pha_maze8.bsr",
			"pha_maze5.bsr",
			"pha_tree08.bsr",
			"pha_tree09.bsr",
			"bagh_mong_tree07.bsr",
			"bagh_mong_rockys02.bsr",
			"bagh_mong_rockys03.bsr",
			"bagh_mong_rockys01.bsr",
			"bagh_mong_rockys04.bsr",
			"bagh_mong_broken03.bsr",
			"st_hamada_rock01_04.bsr",
			"st_hamada_rock01_03.bsr",
			"st_hamada_rock01_01.bsr",
			"st_hamada_rock01_02.bsr",
			"st_arch.bsr",
			"st_saltrock01_04.bsr",
			"st_saltrock01_06.bsr",
			"st_saltrock01_05.bsr",
			"st_saltrock02.bsr",
			"st_saltrock01_01.bsr",
			"st_saltrock01_02.bsr",
			"st_saltrock01_03.bsr",
			"alex_fportal.bsr",
			"euro_esteuro_conch01.bsr",
			"euro_esteuro_conch08.bsr",
			"alex_abumena04.bsr",
			"alex_abumena03.bsr",
			"tre_palm02.bsr",
			"oas_tree_tropic02.bsr",
			"bagh_canyon_tree02.bsr",
			"bagh_canyon_tree01.bsr",
			"bagh_field_longtree04.bsr",
			"bagh_field_longtree03.bsr",
			"bagh_field_longtree02.bsr",
			"piety_gate.bsr",
			"st_hamada_rock02_04.bsr",
			"st_hamada_rock02_02.bsr",
			"st_gate02.bsr",
			"bagh_field_longtree01.bsr",
			"euro_esteuro_oltree02_l1.bsr",
			"euro_esteuro_oltree01_l1.bsr",
			"euro_esteuro_conch02.bsr",
			"euro_esteuro_conch05.bsr",
			"euro_esteuro_conch04.bsr",
			"alex_filedpapaya03.bsr",
			"alex_fieldwood03.bsr",
			"alex_stbridge01.bsr",
			"bagh_field_ceder02.bsr",
			"bagh_field_ceder01.bsr",
			"bagh_field_ceder03.bsr",
			"euro_est euro_godfld_ruin01.bsr",
			"bagh_field_ceder04.bsr",
			"alex_fieldwood02.bsr",
			"alex_filedpapaya01.bsr",
			"alex_filedpapaya02.bsr",
			"euro_est euro_godfld_ruin04.bsr",
			"euro_est euro_godfld_ruin06_01.bsr",
			"euro_esteuro_cw12_01.bsr",
			"alex_burner.bsr",
			"alex_filedpalm03.bsr",
			"euro_constan_box01.bsr",
			"euro_esteuro_tongdummy01.bsr",
			"oas_tarim_rob_b_brid_01.bsr",
			"thief_vill_object12_01.bsr",
			"ruin_takla_tentportal13_01.bsr",
			"oas_kara_obj02.bsr",
			"alex_portal.bsr",
			"ruin_takla_tent03_01.bsr",
			"ruin_takla_tent08_01.bsr",
			"ruin_takla_tent05_01.bsr",
			"jupi_tent_02.bsr",
			"euro_esteuro_bigsadtree03.bsr",
			"asiaminor_haran_top25_01.bsr",
			"rock_mt_capture01.bsr",
			"asiaminor_evil_pao02_01.bsr",
			"asiaminor_haran_top23_01.bsr",
			"asiaminor_haran_top19_01.bsr",
			"asiaminor_haran_top17_01.bsr",
			"asiaminor_haran_top02.bsr",
			"asiaminor_haran_top08.bsr",
			"asiaminor_haran_top10.bsr",
			"euro_esteuro_lawless02_01.bsr",
			"asiaminor_haran_top05_01.bsr",
			"euro_esteuro_lawless01_01.bsr",
			"asiaminor_haran_top14_01.bsr",
			"asiaminor_haran_top12_01.bsr",
			"euro_est euro_godfld_ruin02.bsr",
			"euro_est euro_godfld_ruin09_01.bsr",
			"asiaminor_evil_tent01_01.bsr",
			"asiaminor_evil_ent01_01.bsr",
			"asiaminor_haran_top04_01.bsr",
			"asiaminor_haran_top07.bsr",
			"asiaminor_haran_top15_01.bsr",
			"asiaminor_haran_top13_01.bsr",
			"asiaminor_haran_top16_01.bsr",
			"asiaminor_haran_top22_01.bsr",
			"palace_start01.bsr",
			"palace_start02.bsr",
			"euro_est euro_godfld_ruin08_01.bsr",
			"euro_est euro_godfld_ruin07_01.bsr",
			"asiaminor_haran_top18_01.bsr",
			"desert_start01.bsr",
			"asia minor_beach_ruin06_01.bsr",
			"euro_est euro_godfld_ruin15_01.bsr",
			"asiaminor_lake1_01.bsr",
			"asiaminor_cappa_stonega04.bsr",
			"asiaminor_cappa_stonegc01.bsr",
			"asiaminor_haran_top03.bsr",
			"ruin_takla_b_palm01_01.bsr",
			"asia minor_beach_ruin12_01.bsr",
			"asia minor_beach_ruin03_01.bsr",
			"asia minor_beach_ruin11_01.bsr",
			"asia minor_beach_ruin05_01.bsr",
			"asia minor_beach_ruin04_01.bsr",
			"asiaminor_cappa_stonegb01.bsr",
			"asiaminor_cappa_stone01.bsr",
			"central asia_beeh07_01.bsr",
			"central asia_beeh08.bsr",
			"ruin_takl_whale_gal.bsr",
			"asia minor_beach_ruin02_01.bsr",
			"asiaminor_cappa_stone02.bsr",
			"central asia_beeh04.bsr",
			"central asia_beeh01.bsr",
			"central asia_beeh02.bsr",
			"center asia_field_ob10.bsr",
			"center asia_field_ob07.bsr",
			"center asia_field_st20_01.bsr",
			"center asia_field_st15_01.bsr",
			"center asia_stone09_01.bsr",
			"ruin_takl_whale_head.bsr",
			"euro_constan_bl_01.bsr",
			"euro_constan_bl_04.bsr",
			"euro_esteuro_ph_fbset1_01.bsr",
			"euro_esteuro_ph_fbset5_01.bsr",
			"euro_esteuro_box001_1.bsr",
			"euro_constan_house05_h01.bsr",
			"euro_esteuro_ph_box1.bsr",
			"asiaminor_cappa_stonega03.bsr",
			"euro_esteuro_viking11.bsr",
			"euro_esteuro_viking03.bsr",
			"euro_esteuro_viking_25.bsr",
			"euro_esteuro_dantree_02_01.bsr",
			"euro_constan_house03_h02.bsr",
			"euro_constan_house03_h01.bsr",
			"asiaminor_stone02.bsr",
			"oas_tree_tropical03.bsr",
			"center asia_field_st17_01.bsr",
			"center asia_field_st02_01.bsr",
			"center asia_field_ob04_01.bsr",
			"center asia_field_ob01_01.bsr",
			"center asia_field_ob02_01.bsr",
			"center asia_field_st16_01.bsr",
			"oas_kara_wagone01.bsr",
			"ruin_takla_tent07_01.bsr",
			"euro_esteuro_cons_caswall_wfl_01.bsr",
			"euro_constan_tree02_01.bsr",
			"asiaminor_stone01.bsr",
			"asiaminor_stone03.bsr",
			"asiaminor_theater_column02_03.bsr",
			"asiaminor_theater_column02_01.bsr",
			"asiaminor_theater_column01_07.bsr",
			"center asia_field_ob08.bsr",
			"center asia_field_ob12.bsr",
			"centerasia_pao09_01.bsr",
			"asia minor_beach_ruin07_01.bsr",
			"asia minor_beach_ruin10_01.bsr",
			"asiaminor_stone04.bsr",
			"samarkand_center_01.bsr",
			"center asia_field_ob03_01.bsr",
			"euro_constan_bench01.bsr",
			"euro_constan_house02_h02.bsr",
			"euro_esteuro_ph_fbset6_01.bsr",
			"euro_esteuro_ph_fbset2_01.bsr",
			"euro_esteuro_ph_box3.bsr",
			"asiaminor_theater_gate03_brokenwall01.bsr",
			"center asia_field_st11_01.bsr",
			"center asia_field_st14_01.bsr",
			"cj_grave_normal_01.bsr",
			"cj_grave_common_01.bsr",
			"euro_esteuro_viking15.bsr",
			"euro_esteuro_viking14.bsr",
			"euro_esteuro_viking13.bsr",
			"euro_esteuro_oltree03_m1.bsr",
			"euro_est euro_goldh09_01.bsr",
			"euro_est euro_cemetery03_01.bsr",
			"pha_altar.bsr",
			"c_swamp_tree_dark07.bsr",
			"pha_structure.bsr",
			"tre_pine07_01.bsr",
			"togui_house01.bsr",
			"togui_top01.bsr",
			"togui_house02.bsr",
			"togui_door02.bsr",
			"togui_deco_brigs.bsr",
			"togui_top02.bsr",
			"togui_dung.bsr",
			"togui_burner.bsr",
			"euro_esteuro_upi_02_01.bsr",
			"togui_gate_01.bsr",
			"togui_wall01.bsr"
		};
	}
}
